trackers:
- {name: 'human://CHEST', description: 'human://CHEST'}
- {name: 'human://RIGHT_FOOT', description: 'human://RIGHT_FOOT'}
- {name: 'human://LEFT_FOOT', description: 'human://LEFT_FOOT'}
- {name: 'human://LEFT_KNEE', description: 'human://LEFT_KNEE'}
- {name: 'human://RIGHT_KNEE', description: 'human://RIGHT_KNEE'}
- {name: HMD, description: HMD, designation: HMD}
- {name: 'human://WAIST', description: 'human://WAIST'}
- {name: 'udp://E8:DB:84:99:05:22/adj', description: 'udp://192.168.1.67', designation: 'body:right_leg',
    rotation: FORWARD}
- {name: 'udp://E8:DB:84:99:05:22/1/adj', description: 'udp://192.168.1.67/1', designation: 'body:right_ankle',
    rotation: FORWARD}
- {rotation: FORWARD, name: 'udp://58:BF:25:DA:48:1D/adj', description: 'udp://192.168.1.46',
    designation: 'body:chest'}
- {name: 'udp://58:BF:25:D9:85:D2/adj', description: 'udp://192.168.1.43', designation: 'body:hip',
    rotation: LEFT}
- {rotation: FORWARD, name: 'udp://58:BF:25:DA:48:1D', description: 'udp://192.168.1.46',
    designation: 'body:chest'}
- {rotation: LEFT, name: 'udp://58:BF:25:D9:85:D2', description: 'udp://192.168.1.43',
    designation: 'body:waist'}
- {name: 'udp://94:B9:7E:17:95:1B/adj', description: 'udp://192.168.1.60', designation: 'body:waist',
    rotation: FORWARD}
- {rotation: FORWARD, name: 'udp://94:B9:7E:17:95:1B', description: 'udp://192.168.1.60',
    designation: 'body:waist'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:47:6B/adj', description: 'udp://192.168.1.60',
    designation: 'body:left_leg'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:47:6B/1/adj', description: 'udp://192.168.1.60/1',
    designation: 'body:left_ankle'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:47:6B', description: 'udp://192.168.1.60',
    designation: 'body:chest'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:47:6B/1', description: 'udp://192.168.1.60/1',
    designation: 'body:waist'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:05:22/1', description: 'udp://192.168.1.68/1',
    designation: 'body:right_ankle'}
- {rotation: FORWARD, name: 'udp://E8:DB:84:99:05:22', description: 'udp://192.168.1.68',
    designation: 'body:right_leg'}
bridge:
    steamvr:
        trackers: {right_knee: true, right_foot: true, chest: true, left_foot: true,
            waist: true, left_knee: true}
window: {posx: 1238, posy: 281, width: 1104, height: 909}
keybindings: {reset: CTRL+ALT+SHIFT+Y, quickReset: CTRL+ALT+SHIFT+U}
body:
    footOffset: 0.0
    footLength: 0.05
    waistDistance: 0.05
    headShift: 0.12
    kneeHeight: 0.42499998
    chestDistance: 0.39999998
    neckLength: 0.09
    hipsWidth: 0.28
    torsoLength: 0.79999995
    model: {extendedKnee: false, extendedPelvis: true}
    hipOffset: 0.0
    legsLength: 0.84999996
    skeletonOffset: 0.0
    width: 271
    height: 535
    posx: 981
    posy: 250
zoom: 1.0
laf: com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme
sound: true
ping: false
tps: false
rssi: false
autoskeleton: false
autosteam: false
showraw: false
renderer: {posx: 2325, posy: 385, width: 1111, height: 915}
wifi: {posx: 1677, posy: 13, width: 658, height: 274}
ui: {posx: 1237, posy: 15, width: 458, height: 273}
settings: {posx: 1032, posy: 20, width: 216, height: 239}
showpoints: true
resizepoints: false
resizemultiplier: 83
shownames: true
skeletonscale: 25
