# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SlimeVR Server

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
            submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle' # will restore cache of dependencies and wrappers

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew clean test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
            submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle' # will restore cache of dependencies and wrappers

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Upload the Server JAR as a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: "SlimeVR-Server" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/*
